# Opções comuns para os formulários
common_steps:
  - "Acessar sistema"
  - "Extrair dados"
  - "Processar informações"
  - "Validar resultados"
  - "Gerar relatório"

systems:
  common_tools:
    - "SAP"
    - "Excel"
    - "Outlook"
    - "Teams"
    - "SharePoint"
    - "Power BI"

data_types:
  - "Dados estruturados"
  - "Dados não estruturados"
  - "Documentos"
  - "Imagens"
  - "Planilhas"
  - "Emails"

business_rules_templates:
  - "Validar dados de entrada"
  - "Verificar duplicidade"
  - "Confirmar autorização"
  - "Registrar log de execução"
  - "Notificar em caso de erro"
  - "Backup dos dados processados"

common_exceptions:
  - "Sistema indisponível"
  - "Dados inconsistentes"
  - "Arquivo não encontrado"
  - "Permissão negada"
  - "Timeout de conexão"
  - "Formato inválido"

automation_goals:
  - "Redução de tempo"
  - "Eliminação de erros"
  - "Padronização do processo"
  - "Aumento de produtividade"
  - "Melhoria da qualidade"

kpi_templates:
  - "Tempo médio de processamento"
  - "Taxa de erro"
  - "Volume processado"
  - "Custo por transação"
  - "Satisfação do usuário" 