# Opções comuns para os formulários
common_steps:
  - "Acessar sistema"
  - "Extrair dados"
  - "Processar informações"
  - "Validar resultados"
  - "Gerar relatório"

systems:
  common_tools:
    - "SAP"
    - "Excel"
    - "Outlook"
    - "SharePoint"
    - "OCR"
    - "Portal Receita Federal"
    - "Teams"
    - "Power BI"
    - "Sistema Interno"
    - "Banco de Dados"

data_types:
  - "Dados financeiros"
  - "Documentos fiscais"
  - "Dados cadastrais"
  - "Dados de controle"
  - "Dados pessoais"
  - "Dados estruturados"
  - "Dados não estruturados"
  - "Imagens"
  - "Textos"

data_formats:
  - "PDF"
  - "Excel"
  - "Word"
  - "CSV"
  - "TXT"
  - "JSON"
  - "XML"
  - "Email"
  - "Imagens (JPG/PNG)"
  - "Dados estruturados"

data_sources:
  - "Email"
  - "Sistema SAP"
  - "Sistema OCR"
  - "Portal Receita Federal"
  - "SharePoint"
  - "Planilhas"
  - "Banco de dados"
  - "Arquivos compartilhados"
  - "Sites/Portais"
  - "APIs"

business_rules_templates:
  - "Validar dados de entrada"
  - "Verificar duplicidade"
  - "Confirmar autorização"
  - "Registrar log de execução"
  - "Notificar em caso de erro"
  - "Backup dos dados processados"

common_exceptions:
  - "Sistema indisponível"
  - "Dados inconsistentes"
  - "Arquivo não encontrado"
  - "Permissão negada"
  - "Timeout de conexão"
  - "Formato inválido"

automation_goals:
  - "Redução de tempo"
  - "Eliminação de erros"
  - "Padronização do processo"
  - "Aumento de produtividade"
  - "Melhoria da qualidade"

kpi_templates:
  - "Tempo médio de processamento"
  - "Taxa de erro"
  - "Volume processado"
  - "Custo por transação"
  - "Satisfação do usuário" 